### ISSUE TITLE
Auto play

### ISSUE THREAD

**Issue by ipistissaurabh** [PAIO-CO-KR/carousel-3d#11]
Hi i want this slider in autoplay

**Comment by kyuwoo-choi** [comment]
hi. I want it to be applied, but I suffer lack of hours.

until than you can do it using setInterval and next function.

please refer issue : https://github.com/PAIO-CO-KR/carousel-3d/issues/5

**Comment by cimes** [comment]
See http://cimes.ru/blog/1/17/auto-play-paio-jquery-carousel-3d-ili-kak-sdelat-avto-vraschenie-karuseli/

**Comment by daitranthanhhoa** [comment]
it show error Uncaught TypeError: "[data-carousel-3d]".Carousel3d is not a function
