### ISSUE TITLE
Auto Play Carousel

### ISSUE THREAD

**Issue by cimes** [PAIO-CO-KR/carousel-3d#15]
See http://cimes.ru/blog/1/17/auto-play-paio-jquery-carousel-3d-ili-kak-sdelat-avto-vraschenie-karuseli/

**Comment by kyuwoo-choi** [comment]
good. closing duplicated https://github.com/PAIO-CO-KR/carousel-3d/issues/11

**Comment by kyuwoo-choi** [comment]
btw. I'd be glad if you send pr with your example on readme.md.
thanks :)
