### ISSUE TITLE
Refresh / Append

### ISSUE THREAD

**Issue by maikealame** [PAIO-CO-KR/carousel-3d#18]
Hey nice plugin.

So, I was looking ways to append new itens `<li>` dynamically and found nothing. Has anyway to do this ?
-> append
-> construct / destruct
-> refresh after add

In my case, I use this to show results from a search, a div with pic and texts/buttons. If I remove the wrap and create again the element, the visual effect is not enjoyable. Any idea?

Thanks

**Comment by maikealame** [comment]
Hello again,

I look the sourcecode and use this:

`$('[data-carousel-3d]').Carousel3d("appendChild",$(selector));`

Very good, it's do what I want. But I can't remove without let a space blank from the removed element. So, I edit the sourcecode and create a `removeChild` to use like this:

```
$('[data-carousel-3d]').Carousel3d("removeChild", index );
$('[data-carousel-3d]').Carousel3d("removeChild", ".img_teste" );
$('[data-carousel-3d]').Carousel3d("removeChild", $(".img_teste") );
$('[data-carousel-3d]').Carousel3d("removeChild", element );
```

It can be used, for example, like this:

```
$("#carousel").on('click', "[data-child]", function (e) {
    $('#carousel').Carousel3d(
        "removeChild",
        $( this ).index() // if you pass a index, send the index of [data-child] elements, else send the own element in other cases (see next example)
    );
});

$("#carousel").on('click', ".image", function (e) {
    $('#carousel').Carousel3d(
        "removeChild",
        $( this )
    );
});


```

**Comment by kyuwoo-choi** [comment]
nice. you can the send pull request if you want.
