### ISSUE TITLE
Two panel carousel fails in Firefox

### ISSUE THREAD

**Issue by hiphigi** [PAIO-CO-KR/carousel-3d#21]
Evident here: https://merkd.com/u/danl

Works fine in chrome but not in firefox. In firefox the slides lay over each other and you can only click one of them.

**Comment by kyuwoo-choi** [comment]
hi. I looked into the carousel in your link, and I guess it's because you have only two items.

As you know it's 3d carousel and one lays 0" and the other lays on 180" which totally flipped and shows nothing. just try to add one more and tell me again.

**Comment by hiphigi** [comment]
Yes, that is exactly the issue. It works fine if it has 3 items in it. It also breaks with one item, but that's not really an issue as you can simply not declare it.

However, when there are two items, there is no option to make it display correctly in Firefox. Could you please fix this?

**Comment by kyuwoo-choi** [comment]
em. I just found myself carousel-3d works fine with 2 elements even in firefox then lol.
I think you lost here. It's "carousel-3d" not "jquery-carousel3d" ;)
