### ISSUE TITLE
Remove 3-D Perspective on side images?

### ISSUE THREAD

**Issue by superscotty19** [PAIO-CO-KR/carousel-3d#26]
Hi,
 I LOVE this carousel but my client wants to remove the 3D effect from the sides and just have a regular carousel (essentially the same as what it would look like on older browsers). Can you tell me how to do this? 
Thanks!

**Comment by kyuwoo-choi** [comment]
hey @superscotty19 
It is intended to render 3D from the base. I don't think It can be just on/off the feature.
sorry :(
