### ISSUE TITLE
Rotate multiple instances is not working

### ISSUE THREAD

**Issue by nhkduy90** [PAIO-CO-KR/carousel-3d#5]
I want the Carousel auto rotate after x seconds. I create multiple instance on same page with format
div id="myCarousel" data-carousel-3d

and use this function:

setInterval(function(){
    $('#myCarousel').Carousel3d('next');
}, 3000);

It only works on the first Carousel. Is there any way to make all instance work or improve my script?

Edit: It was my fault. I need to implement an extra script to make it work on multiple instaces, it's not an issue of carousel-3D

**Comment by kyuwoo-choi** [comment]
no problem. I guess calling 'next' method on every carousel should work ok.
ex )
setInterval(function(){
 $('#myCarousel').Carousel3d('next');
 $('#mySecondCarousel').Carousel3d('next');
 $('#myThirdCarousel').Carousel3d('next');
}, 3000);

:)

**Comment by Mountaingal** [comment]
Sorry, I know this thread is supposed to be closed, but I can't find another one that might answer my question. I'm also trying to set a carousel (only one) to auto rotate, but can't seem to get it to work at all with the setInterval function you mention. Is there a specific way (or location) where the function needs to be added in order to auto rotate the carousel?

**Comment by nhkduy90** [comment]
@Mountaingal : Did you include jquery? Put it in a script tag and it'll work.
@kyuwoo-choi : actually, I request it from database, so it's impossible to tag #myFirst #mySecond. This carousel is very good but I think I can't use this since it is too simple. My Customer want it load all product and some product have 1-3 images then the Carousel broken, collapse into a single image. They also want to set rotate interval and on hover, it pause. It really needs to improve if people can use it in their project

**Comment by Mountaingal** [comment]
@nhkduy90 : Ah, yes, the script tag was indeed the problem! I had included it, BUT it was missing the '/' in the closing </script> tag. Now I definitely feel stupid! Thanks for getting me straightened out. 
Being able to add a pause on hover would be excellent, but for the moment I'm just excited that it's rotating on its own. :)

**Comment by cimes** [comment]
See http://cimes.ru/blog/1/17/auto-play-paio-jquery-carousel-3d-ili-kak-sdelat-avto-vraschenie-karuseli/
