### ISSUE TITLE
Topless girl image

### ISSUE THREAD

**Issue by baj84** [PAIO-CO-KR/carousel-3d#6]
I want to show this carousel to a higher up to see if the effect is what they want to achieve. But I can't because you've used a photo of a girl in her bra in a sexy pose, which is semi-NSFW. 

I just wonder how many other professionals you have lost because of it.

**Comment by kyuwoo-choi** [comment]
Oh :) ok let me remove that image.

**Comment by kyuwoo-choi** [comment]
done. you can find it removed.

**Comment by baj84** [comment]
haha legend! :)

**Comment by kyuwoo-choi** [comment]
;)
